### ISSUE TITLE
Status + SAMADB Integration?

### ISSUE THREAD

**Issue by SebKrantz** [Stellenbosch-Econometrics/sarbR#10]
Hi. I see this is a nice package, started a few years back. This could be potentially of value for SAMADB -  which grabs data from EconData, STATSSA and the QB on a weekly basis, harmonizes it through a relational database, and makes it available through R, Python and Julia APIs - if it provides a way to access the monthly releases of SARB data - which I found difficult to access because of the use of JavaScript on the website and missing series codes. 

What is your take on this? Can this package access monthly SARB data and could it be used to build a reliable fetcher for SAMADB?

**Comment by HanjoStudy** [comment]
Hi @SebKrantz,

Thank you for the interest in the package. This package is a pet project of mine I started a few years ago to harmonize the outputs from SARB in a more machine readable format. The package is a wrapper around an API that runs on a small AWS machine that has a daily `cronjob` that automatically looks to see if there is new QB data available via the `RSS` feed. If there is new data, it pulls it, puts it into a DB and then an API endpoint exposes the data. If you want know a bit more about the architecture, there is a very awkward video (with tons of views) of me explaining how I went about building the project [HERE](https://www.youtube.com/watch?v=F0V2F_Au2ek).

When you talk about monthly releases, can you perhaps provide an example(s)? I am comfortable with collecting data form JavaScript, but it would be a bit easier if I: (1) Understand your need for the data, (2) Where the data is made available on the SARBs website and (3) what have you tried and what problems can I help you to overcome. 

I have set up a [template](https://github.com/Stellenbosch-Econometrics/sarbR/issues/new?assignees=&labels=Dataset+Request&projects=&template=data-request.md&title=) for data requests, but its seems like your need is a bit broader?

Can you link me to the `R` package you are referring to: SAMADB? If I can see the code, it should give me a broad idea of how integration could work, or even perhaps how to fully migrate.

**Comment by SebKrantz** [comment]
Ok thanks @HanjoStudy. I'll have a closer look at the package as I find time. FYI SAMADB repo is here: https://github.com/Stellenbosch-Econometrics/SAMADB. You should have access to it. With monthly releases I mean the data here: https://www.resbank.co.za/en/home/what-we-do/statistics/releases/selected-statistics. Does sarbR fetch it?

**Comment by HanjoStudy** [comment]
@SebKrantz ,

Would you mind adding me as a contributor to [SAMADB](https://github.com/Stellenbosch-Econometrics/SAMADB)? I see I dont have access. 

I had a look at the monthly, I was able to get some data out, albeit that automation might take some time. I will be at the university later this month. Ill reach out to you for a coffee if you still in Stellenbosch. Then you can show me what you are building, where its hosted, how data is stored and how I could possibly integrate. It might be easier just to push the data straight onto your DB.

``` r
library(tidyverse)
library(jsonlite)
#> 
#> Attaching package: 'jsonlite'
#> The following object is masked from 'package:purrr':
#> 
#>     flatten

monthly_data <- read_json("~/Downloads/monthly_data.json")

parse_monthly <- function(x){
  x %>% 
    bind_cols() %>% 
    janitor::clean_names()
}

(
  all_results <- sample(monthly_data, 5) %>% 
    map(parse_monthly) %>% 
    bind_rows
)
#> # A tibble: 5 × 10
#>   data_type time_…¹ categ…² categ…³ measu…⁴ value period descr…⁵ forma…⁶ forma…⁷
#>   <chr>     <chr>   <chr>   <chr>   <chr>   <chr> <chr>  <chr>   <chr>   <chr>  
#> 1 MRDMA     MON004… MRDMACO Counte… "Net f… 34 7… 2019/… "Net f… #,##0   MMM, y…
#> 2 MRDMA     MON003… MRDCACE Credit… "Net c… 48 8… 2004/… "Broad… #,##0   MMM, y…
#> 3 MRDMA     MON030… MRDMAPC Percen… "M3"    12,56 1998/… "M3 <b… 0.00    MMM, y…
#> 4 MRDMA     MON008… MRDMAPC Percen… "M0"    7,39  2019/… "M0 - … 0.00    MMM, y…
#> 5 MRDMA     MON003… MRDCACE Credit… " Inve… 4 732 1983/… "Broad… #,##0   MMM, y…
#> # … with abbreviated variable names ¹​time_series_code, ²​category_code,
#> #   ³​category_name, ⁴​measure_name, ⁵​description, ⁶​format_number, ⁷​format_date
```

<sup>Created on 2023-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SebKrantz** [comment]
Hi @HanjoStudy, you should have access now. Ok, so I understand that sarbR also basically fetched the QB from the Excel files. SAMADB currently also does that, so I guess there would be no added value of integrating sarbR at this point?! I’m not in SA anymore. SAMADB ist hosted by codera analytics.

**Comment by HanjoStudy** [comment]
Hi @SebKrantz, 

Ah, I see. Thanks again for reaching out and wanting to integrate some of the data. There might be a conflict of interest if its hosted by Codera and given that they already parse the Excel's, I think there isnt any reason to integrate at this stage. `sarbR` does try to add some value and parse it in a much easier to work format, but not enough to validate integration. That said, if you are ok with it, I am going to close this issue.
