### ISSUE TITLE
Error on token_request()

### ISSUE THREAD

**Issue by ihsaanbassier** [Stellenbosch-Econometrics/sarbR#8]
This is probably a very silly oversight on my part, but I think I'm following your installation instructions carefully and still get the following error when running token_request():
"Error in if (is_http) { : argument is of length zero"

Any advice appreciated, thank you!

**Comment by HanjoStudy** [comment]
Hi, let me explore this error a bit further. My feeling is it is the network that is down. Give me 3 days.

**Comment by ihsaanbassier** [comment]
Wonderful, thank you so much!

**Comment by HanjoStudy** [comment]
It was a networking issue. With this issue I decided to split out my API and docker Nginx configuration. Please reinstall package. I tested and everything seems good on my side.

**Comment by ihsaanbassier** [comment]
Thank you so much! It works perfectly now. Such a wonderful tool, really
appreciate you putting this together!
